FROM maven:3.8-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=build /target/igniteSkills-0.0.1-SNAPSHOT.jar igniteSkills.jar
EXPOSE 3000
ENTRYPOINT ["java", "-jar", "igniteSkills.jar"]